INSERT INTO game_profiles (full_name, ingame_name)
VALUES
('Nguyễn Hải Nam', 'TÔI LÀ 7 TẤN#4466'),
('Hoàng Bảo Ngoc', 'UL Justice Man#1322'),
('Đinh Công Nam', 'MiMiHT#210'),
('Bùi Duy Khánh', 'DyKah1#0909'),
('Vũ Tùng Dương', 'AySau#1008'),
('Nguyễn Trung Hiếu', 'trunghiw147#7512'),
('Nguyễn Minh Đức', 'Yuu#sociu'),
('Trần Đức Lân', 'Thresh ĐườngLáng#2006'),
('Hồ Trần Nam Phong', 'imphokdan #1202'),
('Cao Quốc Thiên Minh', 'Minhh1#2006'),
('Lê Duy Thịnh', 'NEU Shibaa#8888'),
('Vũ Xuân Hùng', 'JAILNOW#120al'),
('Phan Đăng Dương', 'nlinhdangiu#1905'),
('LƯƠNG ĐỨC HƯỞNG', 'manhcris7#VN123'),
('Trần Việt Hưng', 'luoighiten#1427'),
('Đinh Hoàng Sơn', 'Núi#GDS78'),
('Nguyễn Hữu Đức', 'Ezzalion#1608'),
('Trần Duy Anh', 'Kiraya04#MĐV'),
('Vũ Hải Nam', 'Hải Nam#1312'),
('Phạm Hoàng Đức Duy', 'SerenavdWoodsen#0511'),
('Lê Việt Hưng', 'hhhhh#vhung'),
('Đào Đức Minh', 'Spidergodz'),
('Nguyễn Đức Hoàng Phong', 'Viet69 #hphon'),
('Trần Như Ý', 'Tư Mã Như Ý#1710'),
('Nghiêm Đình Hoan', 'hoannghiemm #087'),
('Nguyễn Đăng Long', 'oh haewon#4953'),
('Nguyễn Tuấn Dũng', 'dunglinhh#6769'),
('Lê Vũ Hoàng Anh', 'Kaicute050907#vn2'),
('Nguyễn Mai Khoa', 'NgườiconxứThanh#bakaa'),
('Lâm Tuấn Kiệt', 'SGU Pegasus#2605'),
('Nguyễn Công Đạt', 'Tổng Bí Thư#dec'),
('Nguyễn Tiến Cường', 'CăngTayCaoThủ #NTC'),
('Nguyễn Đình Tuấn', 'Abel de Flan#abel'),
('Nguyễn Hà Chuyên', 'Yiewna#ynk'),
('Trần Mạnh Hoàng', 'HoangTran#2608'),
('Đào Hoàng Hiệp', 'NoHope4U#dhh'),
('Bùi Đại Nghĩa', 'Hồng Trà Kem Mặn#1215'),
('Nguyễn Bình Minh', 'Lucius#07120'),
('Lại Bùi Hoàng Anh', 'TuoiLonAn #40524'),
('Nguyễn Đinh Phú Vinh', 'BTW Molly#vinh'),
('Vương Tiến Dũng', 'gió mùa đông #mthao'),
('Lê Quốc Dũng', 'DũngFlex#1405'),
('Hoàng Hải Long', 'Hết Lòng Vì Em#1412'),
('Phạm Hải Minh', 'ThichGirlTocHong #1204'),
('Lê Dũng', 'simisml2412#2106'),
('Triệu Quốc Hưng', 'HỏiChấm5#265'),
('Đinh Tiến Mạnh', 'LifeSquare#2265'),
('Đoàn Nhật Minh', 'MinhKoVui#YDKL'),
('Nguyễn Mạnh Quyền', 'QuyenDubai#1003'),
('Trần Thuận Hoàn', 'marcuz#tth'),
('Vũ Mạnh Công', 'CÔNG666#66666'),
('Đỗ Thành Tài', 'dtt #2204'),
('Nguyễn Đình Duy', 'Ngauz#1903'),
('Nguyễn Quốc Cường', 'nqcuong#8113'),
('Nguyễn Thanh Long', 'Moo Falo#Falo'),
('Phạm Xuân Bách', 'FaNote#1628'),
('Ngô Chí Dũng', 'Minjeong đáng iu#11201'),
('Trương Hồng Phúc', 'Peter Trương #K34IT'),
('Phạm Minh Quân', '2303200512345678#nguoi'),
('Lê Ngọc Tài', 'T1 Mochi#2106'),
('Lê Duy Dũng', 'ZungSenei#ddl07'),
('Nguyễn Tuấn Minh', 'Chezzy#3006'),
('Nguyễn Duy Quang', 'Toibigamequay#'),
('Phan Phước Khang', 'Cậu Bar Biên Hoà #2005'),
('Vũ Minh Hiếu', 'chxco#chxco'),
('Quách Tuấn Khải', 'Ông Hoàng KíchHệ#2305'),
('Nguyễn Quang Huy', 'Zach Noe#mlem'),
('Đinh Việt Hà', 'ronadinho777#VN2'),
('Trần Thái Bảo Trung', 'Thách đấu CLQ #8445'),
('Phạm Đại Phúc', 'PLSIIDAINN#9539'),
('Nguyễn Đức Kiên', 'DKien#1407'),
('Lê Trường Xuân', 'HếtNợĐổiTên#36205'),
('Nguyễn Gia Huy', 'tduongxinh#361'),
('PHAN PHÚ CƯỜNG', 'UIA#2k1'),
('Nguyễn minh phong', 'Maybeimwrong#3154'),
('Phùng Tiến Đạt', 'VBao#5751'),
('Lê Mạc Huy Tiến', 'TSS Turtle#7777'),
('Nguyễn Việt Hoàng', 'LgNvhcharacter#ASMR'),
('Nguyễn Vĩnh Sơn', 'vinsontheween#210'),
('Nguyễn Bảo Anh', 'pokenanana#9084'),
('Nguyễn Hữu Việt', 'Sin of death#narca'),
('Tạ Thành', 'DoubleD#2511'),
('Phan Đức Huy', 'zZenniSs#GGWP'),
('Võ Phong Hiển', '11 L0 2005#mmbel'),
('Nguyễn Công Vinh', 'vinhnguyen#2486'),
('Phạm Minh Dũng', 'DVRKVI#vn2'),
('Nguyễn Việt Hưng', 'Phương Mỹ Chi#HEHE'),
('Phạm Lê Hiếu', 'Kaajak#8201'),
('Phạm Nguyễn Gia Hưng', 'HưngHưHỏg#zzzz'),
('Lê Khôi Nguyên', 'Zoom#1367'),
('Zemek Filip', 'ZEN Park Ja Hyun#jetph'),
('Doãn Việt Hoàng', 'haihondailuclac#1010'),
('Lê Hồng Nguyên', 'DeadSilence2002#DS002'),
('Phạm Đức Huy', 'T1 6 CUP#2007'),
('Phạm Quang Tú', 'EmGánhNgài#9401'),
('Trần Hoàng Thái', 'hoangthai#0610'),
('Trần Nam Đạt', 'tướng cướp elo#dit'),
('Trần Nam Thành', 'KM đi CKTG#KM1'),
('Vũ Tiến Đức', 'Trần Vũ Anh Thư#16010'),
('Nguyễn Hoàng Tuấn', 'toi se tro lai #0201'),
('Trần Trung Kiên', 'Sniperr#2309'),
('Nguyễn Hoàng Nguyên', 'SSC MissyuKC#0112'),
('Hà Tuấn Anh', 'TuanBeo78#vn2'),
('Nguyễn Xuân Thành', 'sunfyre#2107'),
('Đỗ Xuân Vinh', 'Hoang Thiên Đế#vânhi'),
('Nguyễn Trọng Nghĩa', 'enqhia#279'),
('Tống Minh Nghĩa', 'que1#12345'),
('Nguyễn Quốc Cường', 'QCuong2501#2501'),
('Nguyễn Quốc Phương', 'ĂnThịtNgườiLùn#1725'),
('Trần Hoàng Long', 'Flacko#1st'),
('Lê Anh Khôi', 'REEADY#READY'),
('Nguyễn Nhật Minh', 'Wearepit#0000'),
('Lê Anh Tuấn', 'disappointed #ngu'),
('Vũ Trung Kiên', 'Tội Tày Trời#kiki'),
('Phạm Hải Tuân', 'ChineseDrone01#2506'),
('Nguyễn Vũ Duy', 'Dumpliing #8008'),
('Nguyễn Quang vinh', 'Vinhmoi#49500'),
('Nguyễn Tuấn Khang', 'Khang123456789#love'),
('Nguyễn Đình Tân', 'Tinder Student#99999'),
('Bùi Phương Nam', 'EatToughApple #3007'),
('Trần Văn Anh Tuấn', 'Nallian#7964'),
('Nguyễn Sơn Phi Hoàng', 'OSD s1nDyz#s0va'),
('Trần Thanh Tuấn', 'OnePiece#8253'),
('PHAM MAI TOAN', 'Toàn và 7 dog#2007'),
('Hồ Xuân Hà', 'Marcus06#HXH'),
('Đoàn Tùng Lâm', 'WoodyONFIRE#VN2'),
('Nguyễn Thanh Bình', 'swhhdd#urfav'),
('Phạm Văn Tân', 'Kazu đi CKTG#0603'),
('Đoàn Minh Quân', 'OSD SERIOUSSS#wheru'),
('Bùi Sơn Bách', 'Gira1204#vn2'),
('lê việt dũng', 'vuatrochoia#0000'),
('Nguyễn Như Phong', 'ThayPhongYeuCoAy#99999'),
('Đặng Minh Đức', 'em đức khát máu#miduu'),
('Trần Gia Bảo', 'T1 TRẦN LẢ LƯỚT#1101'),
('Trần Hoàng Yến', 'Quagmire#6996'),
('Phạm Ngọc Khiêm', 'NEUxFennik#vcs'),
('Vũ Gia Bảo', 'funn#hihi'),
('vũ tuấn anh', 'REVO Gaulim#2003'),
('Nguyễn Duy Khoa', 'Phantom#8742k'),
('Nguyễn Quang Kiệt', 'Napoleon the pig#vn2'),
('Đào Việt Duy', 'Luckfoundme#2009'),
('Nguyễn Minh Hiếu', 'She Is Mine#4ever'),
('Nguyễn Trần Bá Nhân', 'Hương Thảo#Cutie'),
('Đoàn Long Nhật', 'SSC D2JP#1129'),
('Trần Văn Công', 'Kong King ĐCTL #GaMi'),
('Nguyễn Nhật Minh', 'Athena ares #5511'),
('Đồng Văn Quốc', 'paws1#SS16'),
('Nguyễn Trọng Ngọc Sáng', 'NL1ght#36363'),
('Cao Đức Thành', 'KuMiu#KuMiu'),
('Lâm Nhật Thanh', 'Em H I G H#2002'),
('Vũ Duy Bình', 'một múi quýt #dungj'),
('Trần Việt Quang', 'Vạn Vật Bên Nhau#25122'),
('Nguyễn Anh Thái', 'sonaki#ntas'),
('Lương Trường Giang', 'Giang Siêu Bự#01205'),
('Nguyễn Văn Cường', 'SGD Cậu Sơn#1996'),
('Nguyễn Trung Kiên', 'kaifox#sahur'),
('Nguyễn Tiến Anh', 'XES 诸葛亮#1701'),
('Lê Thị Quỳnh Ngọc', 'Thỏ Ngọc Đập Đá #2812'),
('Nguyễn Quang Minh', 'beoiucuain#5306'),
('Lê Bá Thanh', 'Rabbit#shin'),
('Trần Gia Huy', 'huytraan2#7907'),
('Tống Duy Bách', 'Keria#K07'),
('Huỳnh Văn Tuyên', 'Vtuyen03#2201P'),
('Phan Đình Vũ', 'Popow#popo'),
('Phạm Quốc Anh', 'Em Quanh Ionia#QaN'),
('Phan Thế Hiệp', 'Thehiep#7807'),
('Đặng Việt Hoàng', 'Lọ Thánh Chí Tôn#Hogan'),
('Nguyễn Mạnh Hoàng', 'Zellow#nmh'),
('Nguyễn Thanh Danh', 'Diamond D#NTD'),
('Phạm Khiêm', 'Inugami#BeMoe'),
('Lê Nhật Minh', 'Bo0#13013'),
('Vũ Ngọc Vinh', 'Boyallchamp#5605'),
('Doãn Hữu Luận', 'Washingmachine#Luan'),
('Trịnh Vũ Công Hiếu', 'Liên Minh Fizz#51205'),
('Tạ Quang Lâm', 'Go Pro#22006'),
('Nguyễn Hoàng Vũ', 'con vật trên top#hehe'),
('Huỳnh Minh Tính', 'Dev1ce#2210'),
('Tạ Hoàng Hiếu', 'Tên tui là Hiếu#10925'),
('Nguyễn Quý Mạnh', 'Arizona MMèo#0511'),
('Lê Hữu Hoàng', 'hh sao vay#famid'),
('Nguyễn Danh Huy', 'KarmaTFT#0312'),
('Vương Khánh Hưng', 'Anh sẽ chờ em#2302'),
('Trần Ngọc Tín', 'MikeCồ Chần#1601'),
('Nguyễn Tiến Minh', 'MinieMim#0210'),
('Đoàn Lê Minh', 'ĐEN VÃI CẢ L#DCMM'),
('Nguyễn Huyền Minh Quang', 'NHMQxNTNK#B2W'),
('Nguyễn Thanh Hiếu', 'nth2005#2565'),
('Nguyễn Đặng Anh Đức', 'Fenomeno#2264'),
('Nguyễn Hà Hưng Thịnh', 'MP thinhh1#1208'),
('Cao Đức Khánh', 'Đầu chôm chôm#21095'),
('Bùi Xuân Sơn', 'Bùi Tổng#0809'),
('Phạm Vinh Quang', 'MP Welwel'),
('Nông xuân dũng', 'so1laangsonn'),
('Lê Thành Đại', 'Wano Oly#0512'),
('Lê Minh Đức', 'leeminhduc2#0475'),
('Nguyễn Quang Khải', 'choco mica#0701'),
('Đồng Tuấn Dương', 'CrazyD#4173'),
('Le Quang Nhat', 'Schhrodinger#2201'),
('nguyen cong duy', 'toithichem#0203'),
('Nguyễn Đình Vũ', 'TOP 1 Tommy#229'),
('Nguyễn Trọng Thư', 'freesoul #Dipan'),
('Trần Đắc Nhật Anh', 'Thuy Bach Duong#VN2'),
('Nguyễn quốc việt', 'NoName111#MDZCC'),
('Nguyễn An Bằng', 'younggboisitinhh#31075'),
('Lưu Tấn Hưng', 'KAVERSE GO RANK1 #1901'),
('Nguyễn Khắc Thành Long', 'ZinZinLoveAkali#akali'),
('Lê Hải Sơn', 'Sơn Bi#99E1'),
('Đậu Xuân Tiến', 'Kasttzy#1202'),
('Bùi Đình Nguyên Ngọc', 'Thỏ Con#6969'),
('Nguyễn Minh Huy', 'チャイルドハンター#0000'),
('Trần Quang Huy', 'greatpresident#gp54'),
('Lê Quang Huy', 'Abc Jkl Xyz 0#TGE'),
('Dương Đức Tâm', 'E LàKhôngThể#2972'),
('Trần Trí Hùng', 'tth050320#VN2'),
('Trần Thành Đạt', 'Moilich#05122'),
('Lê Văn Long', 'Longggg#9999'),
('Đào Nguyễn Hoàng Phú', 'Dhnp2005#Dldk'),
('Ngô Xuân Hùng', 'cơn mưa mèn mén#T1310'),
('Đoàn Văn Dũng', 'yusimty#1309'),
('Nguyễn Đăng Hiếu', 'Người cô ấy chọn#NĐH'),
('Trần Minh Nghĩa', 'Hóa suýt 10 THPT#HCMUT'),
('Lê Huyỳnh Anh Đức', 'Hald#1786'),
('Nguyễn Anh Tú', 'TSE Ben#2611'),
('Nguyễn Đức Anh', 'Inc0ns1stent #325'),
('Phạm Trung Dũng', 'trollypitiu#198'),
('Vũ Hoàng Nam Khánh', 'Krypt#1101'),
('Lê Quang Nhân', 'Sagittarius28#2811'),
('Trần Ngọc Tú', 'TU GOAT1#1500'),
('Nguyễn Viết Tâm', 'Viết Tâm TFT#VTT1'),
('Nguyễn Công Chí', 'Tiểu Thanh Long#Chii1'),
('Phạm Quốc Cường', 'QxCwng#PQC4'),
('Trần Đức Mạnh', 'Đập Lọ Lão Tổ#5511'),
('Lê Duy Quang', 'Qiunxi#Song'),
('Nguyễn Công Quý', 'QyQy1 #1508'),
('Đỗ Hoàng Dương', 'giac mo thachdau#dhd'),
('Nguyễn Tiến Thắng', 'ankiue#1111'),
('Đồng Phúc Luận', 'maggi06#88888'),
('Trần Đức Mạnh', 'ymc1#0720'),
('Trần Kính Tài', 'Game này quay t #1992'),
('Đào Phú Quốc', 'Tôi cắt moi #277'),
('Dương Đức Hiếu', 'Yoo Chimin#00000'),
('Nguyễn An Phú', 'H3rthakA#29L5'),
('Hoàng Minh', 'L0stt#lost'),
('Phạm Đức Anh', 'SoftBoizz#8386'),
('Nguyễn Văn Việt', 'Em Viet toi choi#1409'),
('Lâm An Như Hải', 'NuHa#2006'),
('Đỗ Hoàng Long', 'butpro123sn#21706'),
('Vũ Hải Nam', 'Học cách lặng im'),
('Phạm Minh Tuệ', 'SBLT AnLiễng#0504'),
('Nguyễn Quang Anh', 'yunqa259#2509'),
('Lê Anh Quân', 'Hanry No1#0706'),
('Nguyễn Thành Chung', 'Chungnè Hihi'),
('Nguyễn Trung Hiển', 'Hubr1s#prime'),
('Nguyễn Hữu Hiệp', 'DongMauHoNguyen#3DTL'),
('Trương Đại Dương', 'T1 DuoHuyn#2007'),
('Hoàng Diệu', 'diewhoan#1113_');

INSERT INTO nhibeo (nhibeo_weight) VALUES (9153)  ON DUPLICATE KEY UPDATE id=id
